### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by nod** [sgreben/slack-emoji-upload#3]
I'd like to include some builds of your tool in another project, and link back to your source as a part of it.

Would you please add an open source license so that I know this is ok?

Thank you for the great tool!

**Comment by sgreben** [comment]
Hey, thanks! Added a LICENSE file now (Unlicense/public domain).

**Comment by sgreben** [comment]
Also added a fresh binary release, for good measure. I think it's probably not necessary in terms of licensing, but doesn't hurt either :D

**Comment by nod** [comment]
Most excellent, thank you!

I used your app in my toy chartmoji project.  https://github.com/threatsimple/chartmoji

I have a minor patch to send to you where I added a sleep between each image to help slow down the timeout issues.  I'll try to package that up in the next day or two.
